#!/usr/bin/env ruby
# encoding: UTF-8
require File.expand_path('init', File.dirname(__FILE__))

file = File.expand_path('../schedule.yaml', File.dirname(__FILE__))
Factory.schedule YAML.parser.load(File.read(file))
